spring:
    application:
        name: Customer-Service
    datasource:
        url: jdbc:h2:mem:customer
        username: root
        password: root
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        hibernate:
            ddl-auto: create
        database-platform: org.hibernate.dialect.H2Dialect
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
server:
    port: 8200